version: '3.8'

networks:
  app_metrics:
    driver: bridge

services:

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    #restart: unless-stopped
    #depends_on:
    #  - node_exporter
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_metrics

  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    #restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - app_metrics


  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana_metrics
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/datasources
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - app_metrics 

