global:
  scrape_interval: 15s  # Intervalo de coleta das métricas

scrape_configs:
  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: ['prometheus:9090']  # Prometheus coletando suas próprias métricas

  #- job_name: 'grafana'
  #  static_configs:
  #    - targets: ['grafana:3000']  # Grafana coletando métricas do Grafana

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] # Node Exporter coletando métricas do HOST

  - job_name: 'app_metrics'
    static_configs:
      - targets: ['app_metrics:3001'] # App Metrics coletando métricas da aplicacao de exemplo

