{
 "title": "App Metris",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status Code 200",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_metrics_total_request{statusCode=\"200\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code 500",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_metrics_total_request{statusCode=\"500\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code 200",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_metrics_total_request{statusCode=\"200\"}[1m]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(app_metrics_total_request{statusCode=\"500\"}[1m]))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "User's Online",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_metrics_total_usuarios_logados",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"node_exporter:9100\",mode=\"system\"}[30s])) by (instance) *100"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"node_exporter:9100\",mode=\"user\"}[30s])) by (instance) *100"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"node_exporter:9100\",mode=\"iowait\"}[30s])) by (instance) *100"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"node_exporter:9100\",mode=\"idle\"}[30s])) by (instance))*100"
    }
   ]
  },
  {
   "title": "Tempo de Requisição",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(app_metrics_duracao_request_bucket[1m]))",
     "legendFormat": "Tempo de Requisição"
    }
   ]
  },
  {
   "title": "MEM RUN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"node_exporter:9100\"}"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"node_exporter:9100\"}"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"node_exporter:9100\"}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"node_exporter:9100\"} / (node_memory_MemTotal_bytes{instance=~\"node_exporter:9100\"})))* 100"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"node_exporter:9100\"} - (node_memory_Cached_bytes{instance=~\"node_exporter:9100\"} + node_memory_Buffers_bytes{instance=~\"node_exporter:9100\"} + node_memory_MemFree_bytes{instance=~\"node_exporter:9100\"})"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"node_exporter:9100\"}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"node_exporter:9100\"} - node_memory_MemAvailable_bytes{instance=~\"node_exporter:9100\"}"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"node_exporter:9100\"}"
    }
   ]
  },
  {
   "title": "Live - Sucesso vs Erros",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(app_metrics_total_request{statusCode=\"200\"}[5m]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(app_metrics_total_request{statusCode=\"500\"}[5m]))",
     "legendFormat": "500"
    }
   ]
  }
 ]
}